### ISSUE TITLE
Error: Failed to launch the browser process!

### ISSUE THREAD

**Issue by Joilson** [swaggerexpert/swagger-editor-validate#577]
```yaml
      - name: Validate openapi.yaml
        uses: char0n/swagger-editor-validate@v1
        with:
          swagger-editor-url: http://localhost/
          definition-file: openapi.yaml
```

![image](https://github.com/user-attachments/assets/255485b0-6018-44ff-8853-1f871e23cde9)
